# @package _global_

visual_object_tracking_datasets: /luna_data/zaveri/code/wacv_code/SiamABC/core/dataset_utils #${visual_object_tracking_datasets}


sizes:
  search_image_size: ${tracker.instance_size}
  template_image_size: ${tracker.template_size}
  search_context: ${tracker.search_context}
  search_bbox_ratio: ${tracker.bbox_ratio}
  template_bbox_offset: ${tracker.template_bbox_offset}
  search_image_shift: 48
  search_image_scale: 0.35
  template_image_shift: 8
  template_image_scale: 0.05
  upscale_factor: 2
  context_range: 3

frame_offset: 70
negative_ratio: 0

dynamic_frame_offset:
  start_epoch: 20
  freq: 5
  step: 5
  max_value: 30

train:
  datasets:
    
    # GOT10k
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/GOT10k/GOT10k
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/got10k_vot_excluded_refined.csv #/luna_data/zaveri/code/data/filtered_csvs/filtered_got10k_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 300000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}
    
    # LaSOT
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/LaSOT/LaSOT
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/lasot_refined.csv #/luna_data/zaveri/code/data/filtered_csvs/filtered_lasot_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 100000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    
    # COCO2017
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/coco2017
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/coco2017_refined.csv #/luna_data/zaveri/code/data/filtered_csvs/filtered_coco_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 200000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # # TrackingNet Parts
    # TRAIN_0
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_0_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 200000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_1
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_1_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}
    
    # TRAIN_2
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_2_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}
    
    # TRAIN_3
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_3_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}
    
    # TRAIN_4
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_4_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_5
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_5_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_6
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_6_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_7
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_7_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_8
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_8_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_9
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_9_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_10
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_10_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

    # TRAIN_11
    - dataset_type: ${dataset_type}
      root: ${visual_object_tracking_datasets}/TrackingNet
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: ${visual_object_tracking_datasets}/train_csvs/trackingnet_11_refined.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 50000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}


val:
  img_size: 256
  ann_path:
  datasets:
    # - name: got10k
    #   root_dir: ${visual_object_tracking_datasets}/GOT10k
    #   subset: val
    # - name: nfs
    #   root_dir: ${visual_object_tracking_datasets}/NFS
    - name: vot
      root_dir: vot2018
      version: 2018
    # - name: lasot
    #   root_dir: ${visual_object_tracking_datasets}/LaSOT
    #   file_path: ${visual_object_tracking_datasets}/testing_set.txt
    #   choose: 50
    # - name: trackingnet
    #   root_dir: ${visual_object_tracking_datasets}/TrackingNet
    #   chunk_folder: TRAIN_11
    #   choose: 50
test:
  img_size: 256
  ann_path:
  datasets:
    - name: vot
      root_dir: vot2018
      version: 2018
    # - name: got10k
    #   root_dir: ${visual_object_tracking_datasets}/GOT10k
    #   subset: test
    # - name: got10k
    #   root_dir: ${visual_object_tracking_datasets}/GOT10k
    #   subset: val
    # - name: nfs
    #   root_dir: ${visual_object_tracking_datasets}/NFS
    #   fps: 240
    # - name: lasot
    #   root_dir: ${visual_object_tracking_datasets}/LaSOT
    #   file_path: ${visual_object_tracking_datasets}/testing_set.txt
    #   choose: 50
    # - name: trackingnet
    #   root_dir: ${visual_object_tracking_datasets}/TrackingNet
    #   chunk_folder: TRAIN_11