# @package _global_

sizes:
  search_image_size: ${tracker.instance_size}
  template_image_size: ${tracker.template_size}
  search_context: ${tracker.search_context}
  search_bbox_ratio: ${tracker.bbox_ratio}
  template_bbox_offset: ${tracker.template_bbox_offset}
  search_image_shift: 48
  search_image_scale: 0.35
  template_image_shift: 8
  template_image_scale: 0.05
  upscale_factor: 2
  context_range: 3

frame_offset: 70
negative_ratio: 0
# clip_range: True

dynamic_frame_offset:
  start_epoch: 20
  freq: 5
  step: 5
  max_value: 30

train:
  datasets:
    
   
    # # LaSOT
    - dataset_type: ${dataset_type}
      root: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT
      sampling:
        _target_: core.utils.sampler.TrackSampler
        data_path: /new_local_storage/zaveri/code/old_AEVT_copy/core/dataset_utils/lasot.csv #/new_local_storage/zaveri/code/data/filtered_csvs/filtered_lasot.csv
        negative_ratio: ${negative_ratio}
        frame_offset: ${frame_offset}
        num_samples: 100000 # 100000
      transform: photometric
      regression_weight_label_size: ${tracker.score_size}
      sizes: ${sizes}
      stride: ${model.stride}

   

val:
  img_size: 256
  ann_path:
  datasets:
    # - name: got10k
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/GOT10k/GOT10k
    #   subset: val
    # - name: nfs
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/NFS/NFS/NFS
    # - name: vot
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/vot2018
    #   version: 2018
    - name: lasot
      root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT
      file_path: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT/testing_set.txt
      choose: 50
    # - name: trackingnet
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/TrackingNet
    #   chunk_folder: TRAIN_11
test:
  img_size: 256
  ann_path:
  datasets:
#     - name: vot
#       root_dir: ${visual_object_tracking_datasets}/vot2018
#       version: 2018
    # - name: got10k
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/GOT10k/GOT10k
    #   subset: val
    - name: lasot
      root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT
      file_path: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT/testing_set.txt
      choose: 50
    # - name: vot
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/vot2018
    #   version: 2018
    # - name: nfs
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/NFS/NFS/NFS
    #   fps: 240
    # - name: lasot
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT
    #   file_path: /new_local_storage/zaveri/SOTA_Tracking_datasets/LaSOT/LaSOT/testing_set.txt
    # - name: trackingnet
    #   root_dir: /new_local_storage/zaveri/SOTA_Tracking_datasets/TrackingNet
    #   chunk_folder: TRAIN_11