# @package _global_
phase: train
task: Visual Object Tracking

sampler: none
min_epochs: 100
max_epochs: 150
early_stopping: 20
batch_size:
  train: 32
  val: 1
num_workers: 32
save_top_k: 3
lr: 0.0001
parallel: False
num_classes: 1

metric_to_monitor: valid/metrics/box_iou
metric_mode: max

replace_sampler_ddp: False

best_worst_miner:
  max_images: 16
  metric_to_monitor: loss
  metric_mode: min
